"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PacketType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PacketTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PacketType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _PacketType.ValueType  # 0
    DENY: _PacketType.ValueType  # 1
    LOGIN: _PacketType.ValueType  # 2
    REGISTER: _PacketType.ValueType  # 3
    CHAT: _PacketType.ValueType  # 4
    POSITION: _PacketType.ValueType  # 5
    DIRECTION: _PacketType.ValueType  # 6
    """Add more packet types here"""

class PacketType(_PacketType, metaclass=_PacketTypeEnumTypeWrapper):
    """Define an enum for packet types"""

OK: PacketType.ValueType  # 0
DENY: PacketType.ValueType  # 1
LOGIN: PacketType.ValueType  # 2
REGISTER: PacketType.ValueType  # 3
CHAT: PacketType.ValueType  # 4
POSITION: PacketType.ValueType  # 5
DIRECTION: PacketType.ValueType  # 6
"""Add more packet types here"""
global___PacketType = PacketType

@typing_extensions.final
class OkPacket(google.protobuf.message.Message):
    """Define your packet messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___OkPacket = OkPacket

@typing_extensions.final
class DenyPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REASON_FIELD_NUMBER: builtins.int
    reason: builtins.str
    def __init__(
        self,
        *,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason", b"reason"]) -> None: ...

global___DenyPacket = DenyPacket

@typing_extensions.final
class LoginPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "username", b"username"]) -> None: ...

global___LoginPacket = LoginPacket

@typing_extensions.final
class RegisterPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "username", b"username"]) -> None: ...

global___RegisterPacket = RegisterPacket

@typing_extensions.final
class ChatPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSG_FIELD_NUMBER: builtins.int
    msg: builtins.str
    def __init__(
        self,
        *,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg"]) -> None: ...

global___ChatPacket = ChatPacket

@typing_extensions.final
class PositionPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___PositionPacket = PositionPacket

@typing_extensions.final
class DirectionPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___DirectionPacket = DirectionPacket

@typing_extensions.final
class Packet(google.protobuf.message.Message):
    """Define the main Packet message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    OK_FIELD_NUMBER: builtins.int
    DENY_FIELD_NUMBER: builtins.int
    LOGIN_FIELD_NUMBER: builtins.int
    REGISTER_FIELD_NUMBER: builtins.int
    CHAT_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    type: global___PacketType.ValueType
    @property
    def ok(self) -> global___OkPacket: ...
    @property
    def deny(self) -> global___DenyPacket: ...
    @property
    def login(self) -> global___LoginPacket: ...
    @property
    def register(self) -> global___RegisterPacket: ...
    @property
    def chat(self) -> global___ChatPacket: ...
    @property
    def position(self) -> global___PositionPacket: ...
    @property
    def direction(self) -> global___DirectionPacket:
        """Add more packet types here"""
    def __init__(
        self,
        *,
        type: global___PacketType.ValueType = ...,
        ok: global___OkPacket | None = ...,
        deny: global___DenyPacket | None = ...,
        login: global___LoginPacket | None = ...,
        register: global___RegisterPacket | None = ...,
        chat: global___ChatPacket | None = ...,
        position: global___PositionPacket | None = ...,
        direction: global___DirectionPacket | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chat", b"chat", "deny", b"deny", "direction", b"direction", "login", b"login", "ok", b"ok", "position", b"position", "register", b"register", "subpacket", b"subpacket"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chat", b"chat", "deny", b"deny", "direction", b"direction", "login", b"login", "ok", b"ok", "position", b"position", "register", b"register", "subpacket", b"subpacket", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["subpacket", b"subpacket"]) -> typing_extensions.Literal["ok", "deny", "login", "register", "chat", "position", "direction"] | None: ...

global___Packet = Packet
