"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class OkPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___OkPacket = OkPacket

@typing_extensions.final
class DenyPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REASON_FIELD_NUMBER: builtins.int
    reason: builtins.str
    def __init__(
        self,
        *,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason", b"reason"]) -> None: ...

global___DenyPacket = DenyPacket

@typing_extensions.final
class LoginPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "username", b"username"]) -> None: ...

global___LoginPacket = LoginPacket

@typing_extensions.final
class RegisterPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "username", b"username"]) -> None: ...

global___RegisterPacket = RegisterPacket

@typing_extensions.final
class ChatPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSG_FIELD_NUMBER: builtins.int
    msg: builtins.str
    def __init__(
        self,
        *,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg"]) -> None: ...

global___ChatPacket = ChatPacket

@typing_extensions.final
class PositionPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___PositionPacket = PositionPacket

@typing_extensions.final
class DirectionPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___DirectionPacket = DirectionPacket

@typing_extensions.final
class Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    DENY_FIELD_NUMBER: builtins.int
    LOGIN_FIELD_NUMBER: builtins.int
    REGISTER_FIELD_NUMBER: builtins.int
    CHAT_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    @property
    def ok(self) -> global___OkPacket: ...
    @property
    def deny(self) -> global___DenyPacket: ...
    @property
    def login(self) -> global___LoginPacket: ...
    @property
    def register(self) -> global___RegisterPacket: ...
    @property
    def chat(self) -> global___ChatPacket: ...
    @property
    def position(self) -> global___PositionPacket: ...
    @property
    def direction(self) -> global___DirectionPacket: ...
    def __init__(
        self,
        *,
        ok: global___OkPacket | None = ...,
        deny: global___DenyPacket | None = ...,
        login: global___LoginPacket | None = ...,
        register: global___RegisterPacket | None = ...,
        chat: global___ChatPacket | None = ...,
        position: global___PositionPacket | None = ...,
        direction: global___DirectionPacket | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chat", b"chat", "deny", b"deny", "direction", b"direction", "login", b"login", "ok", b"ok", "position", b"position", "register", b"register", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chat", b"chat", "deny", b"deny", "direction", b"direction", "login", b"login", "ok", b"ok", "position", b"position", "register", b"register", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type", b"type"]) -> typing_extensions.Literal["ok", "deny", "login", "register", "chat", "position", "direction"] | None: ...

global___Packet = Packet
